### PR TITLE
Issue with Disconnect() method [JIRA: CLIENTS-525]

### PR DESCRIPTION
**Pull request by josephjeganathan**
Currently RiakPbcSocket is using disposed NetworkStream and keep failing
- When node goes offline
- When cluster refuses the socket connection

### CODE REVIEW

**Comment by josephjeganathan** [comment]
Long story short:
We were trying to do a proof od concept to riak for a system with high volume of traffic. We set up a cluster with 3 nodes and used ricket .net client with 20 connection each connection pool.

Our cluster machines were reaching their CPU limits and started getting connection errors (which may practically possible for other systems too).

The first error we got was 
```
{"Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
    [System.IO.IOException]: {"Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
    Data: {System.Collections.ListDictionaryInternal}
    HelpLink: null
    HResult: -2146232800
    InnerException: {"A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond"}
    Message: "Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."
    Source: "System"
    StackTrace: "   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at RiakClient.Comms.RiakPbcSocket.ReceiveAll(Byte[] resultBuffer) in C:\src\RiakClient\Comms\RiakPbcSocket.cs:line 368
   at RiakClient.Comms.RiakPbcSocket.ReceiveHeader(Int32& size) in C:\src\RiakClient\Comms\RiakPbcSocket.cs:line 196
   at RiakClient.Comms.RiakPbcSocket.DoRead(MessageCode expectedCode, Type expectedType) in C:\src\RiakClient\Comms\RiakPbcSocket.cs:line 159
   at RiakClient.Comms.RiakPbcSocket.Read(IRiakCommand command) in C:\src\RiakClient\Comms\RiakPbcSocket.cs:line 124
   at RiakClient.Comms.RiakConnection.<>c__DisplayClass3.<Execute>b__1() in C:\src\RiakClient\Comms\RiakConnection.cs:line 291
   at RiakClient.Comms.RiakConnection.DoExecute(Func`1 socketFunc) in C:\src\RiakClient\Comms\RiakConnection.cs:line 312"  TargetSite: {Int32 Read(Byte[], Int32, Int32)}
```

Since the exception the client disposes the connection here: https://github.com/basho/riak-dotnet-client/blob/develop/src/RiakClient/Comms/RiakConnection.cs#L144

Every calls to `PbcWrite` after that was using the disposed `NetworkStream`.

```
System.ObjectDisposedException was caught
  HResult=-2146232798
  Message=Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
  Source=System
  ObjectName=System.Net.Sockets.NetworkStream
  StackTrace:
       at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
       at RiakClient.Comms.RiakPbcSocket.Write(MessageCode messageCode) in c:\src\RiakClient\Comms\RiakPbcSocket.cs:line 83
       at RiakClient.Comms.RiakConnection.PbcWrite(MessageCode messageCode) in c:\src\RiakClient\Comms\RiakConnection.cs:line 159
  InnerException: 

```

This minor fix to set the `networkStream = null` will create new network streams on failure, BUT it may have some other implications. Please review it carefully and merge it if that sounds good.

In my humble opinion, Exponential backoff can be introduced at a situations where server refuses connections due to load/etc.

**Comment by lukebakken** [comment]
Thank you @josephjeganathan, this looks like a good fix to have for this issue.

**Comment by josephjeganathan** [comment]
Hi @lukebakken 

Is there any chance that we can ship to to the Nuget?

Thanks

**Comment by alexmoore** [comment]
Hi @josephjeganathan, I've promoted the build to Nuget:  https://www.nuget.org/packages/RiakClient/2.1.1  

Thanks for the PR!

**Pull request merged**
