### PR TITLE
Improvement to language around contribution

### PR DESCRIPTION
**Pull request by mjbrender**
Finding that language on client library repos can be tweaked a little from others like riak_kv. Here are the results.

### CODE REVIEW

**Comment by alexmoore** [comment]
+1

**Comment by mjbrender** [comment]
Thanks @alexmoore. What's the policy on merging? Is it a +1 and then self-merge or is there a specific maintainer? Might as well learn the rules publicly here :smile:

**Comment by alexmoore** [comment]
+1 and then a self-merge, unless it's an external submission then we'll do the merge.

**Comment by mjbrender** [comment]
:+1:

**Pull request merged**
